services:
  mysql:
    image: mysql:8.0.33
    container_name: employee-server-mysql
    environment:
      MYSQL_DATABASE: employee-server
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: employee-server-user
      MYSQL_PASSWORD: secret_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - employee-server-network

volumes:
  mysql-data:

networks:
  employee-server-network:
    driver: bridge
